# 이 AWS SAM 템플릿은 함수 구성에서 생성되었습니다. 함수에 트리거가 하나 이상 있는 경우 이러한 트리거와 관련된 AWS 리소스가 이
# 템플릿에 완전히 지정되어 있지 않으며 자리 표시자 값도 포함된다는 점에 유의하십시오. AWS Application Composer 또는 선호하는
# IDE에서 이 템플릿을 열고 다른 AWS 리소스와 함께 서버리스 애플리케이션을 지정하도록 수정하십시오.
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  xbeagleSNS:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
        DestinationConfig:
          OnFailure:
            Destination:
              Ref: SNSTopicDestinationFailure1
            Type: SNS
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - iam:GetRole
                - iam:PassRole
              Resource: arn:aws:iam::account-id:role/EC2-roles-for-XYZ-*
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:ap-northeast-2:907729080149:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:ap-northeast-2:907729080149:log-group:/aws/lambda/x-beagle_SNS:*
            - Action:
                - sns:*
              Effect: Allow
              Resource: '*'
            - Sid: EventBridgeActions
              Effect: Allow
              Action:
                - events:*
                - schemas:*
                - scheduler:*
                - pipes:*
              Resource: '*'
            - Sid: IAMCreateServiceLinkedRoleForApiDestinations
              Effect: Allow
              Action:
                - iam:CreateServiceLinkedRole
              Resource: >-
                arn:aws:iam::*:role/aws-service-role/AmazonEventBridgeApiDestinationsServiceRolePolicy
              Condition:
                StringEquals:
                  iam:AWSServiceName: apidestinations.events.amazonaws.com
            - Sid: IAMCreateServiceLinkedRoleForAmazonEventBridgeSchemas
              Effect: Allow
              Action:
                - iam:CreateServiceLinkedRole
              Resource: >-
                arn:aws:iam::*:role/aws-service-role/schemas.amazonaws.com/AWSServiceRoleForSchemas
              Condition:
                StringEquals:
                  iam:AWSServiceName: schemas.amazonaws.com
            - Sid: SecretsManagerAccessForApiDestinations
              Effect: Allow
              Action:
                - secretsmanager:CreateSecret
                - secretsmanager:UpdateSecret
                - secretsmanager:DeleteSecret
                - secretsmanager:GetSecretValue
                - secretsmanager:PutSecretValue
              Resource: arn:aws:secretsmanager:*:*:secret:events!*
            - Sid: IAMPassRoleAccessForEventBridge
              Effect: Allow
              Action:
                - iam:PassRole
              Resource: arn:aws:iam::*:role/*
              Condition:
                StringLike:
                  iam:PassedToService: events.amazonaws.com
            - Sid: IAMPassRoleAccessForScheduler
              Effect: Allow
              Action:
                - iam:PassRole
              Resource: arn:aws:iam::*:role/*
              Condition:
                StringLike:
                  iam:PassedToService: scheduler.amazonaws.com
            - Sid: IAMPassRoleAccessForPipes
              Effect: Allow
              Action:
                - iam:PassRole
              Resource: arn:aws:iam::*:role/*
              Condition:
                StringLike:
                  iam:PassedToService: pipes.amazonaws.com
      SnapStart:
        ApplyOn: None
      Events:
        EventBridgeRule1:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.s3
              detail-type:
                - AWS API Call via CloudTrail
              detail:
                eventSource:
                  - s3.amazonaws.com
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
  SNSTopicDestinationFailure1:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: SNSTopicDestinationFailure1
      KmsMasterKeyId:
        Ref: KMSKeyForSNSDestinationFailure1
  KMSKeyForSNSDestinationFailure1:
    Type: AWS::KMS::Key
